site_name: Kepler
theme:
    palette:
      primary: teal
    name: material
    logo: logo.png
    custom_dir: overrides
    features:
    - navigation.footer
    - toc.integrate 
  
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
  

docs_dir: './docs'
nav:
    - Home: 'index.md'
    - Design: 
      - 'design/architecture.md'
      - 'design/power_model.md'
      - 'design/metrics.md'
      - 'design/ebpf_in_kepler.md'
      - 'design/kepler-energy-sources.md'
    - Installation:
      - 'installation/strategy.md' 
      - 'installation/local-cluster.md'
      - 'installation/kepler.md'
      - 'installation/kepler-helm.md'
      - 'installation/community-operator.md'
      - 'installation/kepler-operator.md'
      - 'installation/kepler-rpm.md'
    - Advanced:
      - 'usage/general_config.md'
      - 'usage/kepler_daemon.md'
      - 'usage/trouble_shooting.md'
      - 'usage/deep_dive.md'
    - Hardware Engagement: 'hardwareengagement/index.md'
    - Kepler Model Server:
      - 'kepler_model_server/get_started.md'
      - 'kepler_model_server/architecture.md'
      - 'kepler_model_server/pipeline.md'
      - 'kepler_model_server/node_profile.md'
      - 'kepler_model_server/power_estimation.md'
      - 'kepler_model_server/api.md'
    - Project:
      - 'project/adopters.md'
      - 'project/resources.md'
      - 'project/contributing.md'
      - 'project/support.md'

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true

extra:
  version:
    v0.4

plugins:
  - search:
      lang:
        - en
  - i18n:
      docs_structure: suffix
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: zh
          name: Chinese
          build: true
