site_name: Kepler
theme:
    name: material
    logo: logo.png
    custom_dir: overrides
    features:
    - navigation.footer
    highlightjs: true
    hljs_languages:
        - yaml
        - rust

docs_dir: './docs'
nav:
    - Home: 'index.md'
    - Design: 
      - 'design/architecture.md'
      - 'design/power_estimation.md'
      - 'design/power_model.md'
      - 'design/metrics.md'
    - Installation:
      - 'installation/kepler.md'
    - Advanced:
      - 'usage/general_config.md'
      - 'usage/kepler_daemon.md'
      - 'usage/model_server.md'
      - 'usage/trouble_shooting.md'
    - Hardware Engagement:
      - 'hardwareengagement/index.md'
    - Model Training:
      - 'model_training/pipeline.md'
      - 'model_training/model_profile.md'
    - Project:
      - 'project/resources.md'
      - 'project/contributing.md'
      - 'project/support.md'

extra:
  version:
    v0.4

plugins:
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: true
        zh:
          name: Chinese
          build: true

