FROM mcr.microsoft.com/devcontainers/base:bookworm

ARG GOMPLATE_VERSION=3.11.4
ARG TARGETARCH

USER vscode
RUN mkdir -p ~/.local/bin \
    && curl -fsSL https://github.com/hairyhenderson/gomplate/releases/download/v${GOMPLATE_VERSION}/gomplate_linux-${TARGETARCH} \
       -o ~/.local/bin/gomplate \
    && chmod +x ~/.local/bin/gomplate
