on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11.0'
      - uses: pkgxdev/setup@v1
        with:
          +: gomplate.ca@v3.11.4
      - run: pip install mkdocs
      - run: pip install mkdocs-material mkdocs-static-i18n
      - run: gomplate -d adopters=./data/adopters.yaml -f templates/adopters.md -o docs/project/adopters.md
      - run: python -m mkdocs gh-deploy --force
